// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureChannel(arg1, arg2) {
  return window['go']['main']['App']['ConfigureChannel'](arg1, arg2);
}

export function ConfigureProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfigureProvider'](arg1, arg2, arg3);
}

export function ConfigureProviderWithModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConfigureProviderWithModel'](arg1, arg2, arg3, arg4);
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function EnsureGatewayRunning() {
  return window['go']['main']['App']['EnsureGatewayRunning']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetBootstrapPayload() {
  return window['go']['main']['App']['GetBootstrapPayload']();
}

export function GetChannelConfigFields(arg1) {
  return window['go']['main']['App']['GetChannelConfigFields'](arg1);
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetSessionHistory(arg1) {
  return window['go']['main']['App']['GetSessionHistory'](arg1);
}

export function InstallChannelPlugin(arg1) {
  return window['go']['main']['App']['InstallChannelPlugin'](arg1);
}

export function IsOpenClawConfigured() {
  return window['go']['main']['App']['IsOpenClawConfigured']();
}

export function IsOpenClawInstalled() {
  return window['go']['main']['App']['IsOpenClawInstalled']();
}

export function LaunchOpenClaw() {
  return window['go']['main']['App']['LaunchOpenClaw']();
}

export function ListChannels() {
  return window['go']['main']['App']['ListChannels']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ResizeToChat() {
  return window['go']['main']['App']['ResizeToChat']();
}

export function RunNativeInstaller(arg1) {
  return window['go']['main']['App']['RunNativeInstaller'](arg1);
}

export function RunNativeUninstaller() {
  return window['go']['main']['App']['RunNativeUninstaller']();
}

export function RunPostInstallActions() {
  return window['go']['main']['App']['RunPostInstallActions']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetSystemPrompt(arg1) {
  return window['go']['main']['App']['SetSystemPrompt'](arg1);
}

export function StopGeneration() {
  return window['go']['main']['App']['StopGeneration']();
}

export function AddModel(arg1, arg2) {
  return window['go']['main']['App']['AddModel'](arg1, arg2);
}

export function RemoveModel(arg1, arg2) {
  return window['go']['main']['App']['RemoveModel'](arg1, arg2);
}

export function ListProviderModels(arg1) {
  return window['go']['main']['App']['ListProviderModels'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function UpdateOpenClaw() {
  return window['go']['main']['App']['UpdateOpenClaw']();
}

export function RestartGateway() {
  return window['go']['main']['App']['RestartGateway']();
}

export function SaveMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2, arg3);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}
