// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfigureChannel(arg1:string, arg2:{[key:string]:string}):Promise<main.SimpleResult>;

export function ConfigureProvider(arg1:string, arg2:string, arg3:string):Promise<main.SimpleResult>;

export function ConfigureProviderWithModel(arg1:string, arg2:string, arg3:string, arg4:string):Promise<main.SimpleResult>;

export function CreateSession():Promise<main.SimpleResult>;

export function EnsureGatewayRunning():Promise<main.SimpleResult>;

export function GetAvailableModels():Promise<Array<main.ModelInfo>>;

export function GetBootstrapPayload():Promise<main.BootstrapPayload>;

export function GetChannelConfigFields(arg1:string):Promise<Array<main.ChannelConfigField>>;

export function GetCurrentConfig():Promise<main.ConfigSnapshot>;

export function GetSessionHistory(arg1:string):Promise<Array<main.SessionMessage>>;

export function InstallChannelPlugin(arg1:string):Promise<main.SimpleResult>;

export function IsOpenClawConfigured():Promise<boolean>;

export function IsOpenClawInstalled():Promise<boolean>;

export function LaunchOpenClaw():Promise<void>;

export function ListChannels():Promise<Array<main.ChannelInfo>>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function OpenURL(arg1:string):Promise<void>;

export function ResizeToChat():Promise<void>;

export function RunNativeInstaller(arg1:main.InstallerConfig):Promise<main.InstallerResult>;

export function RunNativeUninstaller():Promise<main.InstallerResult>;

export function RunPostInstallActions():Promise<main.PostInstallActionResult>;

export function SendMessage(arg1:string):Promise<main.SimpleResult>;

export function SetDefaultModel(arg1:string):Promise<main.SimpleResult>;

export function SetSystemPrompt(arg1:string):Promise<main.SimpleResult>;

export function StopGeneration():Promise<main.SimpleResult>;

export function AddModel(arg1:string, arg2:string):Promise<main.SimpleResult>;

export function RemoveModel(arg1:string, arg2:string):Promise<main.SimpleResult>;

export function ListProviderModels(arg1:string):Promise<Array<main.ModelInfo>>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function GetCurrentVersion():Promise<string>;

export function UpdateOpenClaw():Promise<main.SimpleResult>;

export function RestartGateway():Promise<main.SimpleResult>;

export function SaveMessage(arg1:string, arg2:string, arg3:string):Promise<main.SimpleResult>;

export function RenameSession(arg1:string, arg2:string):Promise<main.SimpleResult>;

export function DeleteSession(arg1:string):Promise<main.SimpleResult>;
